### PR TITLE
Update bootstrap and JQuery library versions

### PR DESCRIPTION
**Pull request by CamileDahdah**
*Issue:* This change is to address the AppSec ticket saying that we need to update our Bootstrap and JQuery dependencies for security purposes. 

*Description of changes:* Updated Bootstrap v3.3.7 to v3.4.1 and JQuery v.3.3.1 to v.3.6.1 and updated relating references in _Layout.cshtml

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by peterrsongg** [comment]
@CamileDahdah For some reason I'm unable to build the sample solution. 

cdahdah-updatedependencies

**Comment by CamileDahdah** [comment]
> @CamileDahdah For some reason I'm unable to build the sample solution. Does it build for you? cdahdah-updatedependencies

Yup, this project seems to be broken already (before I made any change). I am going to meet with Ashish today to see if there is a way to test my changes

**Comment by peterrsongg** [comment]
I tested that this worked by running the sample solution and ensuring the bootstrap and jquery versions were up to date and that there were no errors.

**Comment by CamileDahdah** [comment]
Tested it with the help of Ashish. Proof:
Capture
Capture2

**Review by philasmar — APPROVED** [review]

**Pull request merged**
